on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check git tags
        run: |
          git fetch --all
          git tag
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.100-preview.7.21379.14
      - name: Test
        run: dotnet test --configuration Release --no-build
        working-directory: ./src
      - name: Build
        run: dotnet pack --configuration Release
        working-directory: ./src
