on:
  push:
    tags: 
      - '*'
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-rc.2.21505.57
      - name: run minver
        id: version
        uses: thefringeninja/action-minver@2.0.0-preview1
        with:
          # Optional. Specifies which part of the version to auto-increment.
          auto-increment: minor
          # Optional. Sets custom build metadata for your semantic version.
          #build-metadata: ${{ github.sha }}
          # Optional. Specifies the default pre-release phase.
          default-pre-release-phase: preview
          # Optional. Specifies the minimum version to use when no tags exist.
          #minimum-major-minor: 2.0.0
          # Optional. Specifies the prefix of the tags
          #tag-prefix: v
          # Optional. Specifies the log level.
          verbosity: info
      - name: output
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Test
        run: |
          dotnet test --configuration Release --no-build
        working-directory: ./src
        env:
          MinVerVersionOverride: ${{ steps.version.outputs.version }}
      - name: Pack
        run: |
          dotnet restore
          dotnet msbuild -t:Replace -t:MinVer    
          dotnet pack --configuration Release
        working-directory: ./src
        env:
          MinVerVersionOverride: ${{ steps.version.outputs.version }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .vs/bin/Stelzi79.NetSdk**/Release/**.nupkg
          prerelease: false
        env:
          MinVerVersionOverride: ${{ steps.version.outputs.version }}
#      - name: PreRelease
#        uses: softprops/action-gh-release@v1
#        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
#        with:
#          name: ${{ github.ref_type }}->${{ github.ref_name }} (Sha ${{ steps.short-sha.outputs.sha }}, Run ${{ github.run_id }})
#          tag_name: ${{ steps.version.outputs.version }}-${{ github.run_id }}-${{ github.ref_type }}-${{ github.ref_name }}-${{ steps.short-sha.outputs.sha }}
#          body: |
#            ${{ github.event.commits[0].message }}
#            ${{ toJSON(github.event.commits) }}
#            ${{ toJSON(steps.Pack.outputs) }}
#          files: |
#           .vs/bin/Stelzi79.NetSdk**/Release/**.nupkg
#          prerelease: true
#      - name: Publish the package to GPR
#        run: dotnet nuget push .vs/bin/**/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://nuget.pkg.github.com/Stelzi79/index.json
#        env:
#          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish the package to nuget.org
        run: dotnet nuget push .vs/bin/**/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
