on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.*
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./src
      - name: Test
        run: dotnet test --configuration Release --no-build
