on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
           dotnet-version: 6.0.100-preview.7.21379.14
      - name: Test
        run: |
          dotnet test --configuration Release --no-build
        working-directory: ./src
      - name: Pack and Push to Nuget
        run: |
          dotnet pack --configuration Release
        working-directory: ./src
      - name: Publish the package to GPR
        run: |
          ls  .vs/bin/**/Release/*.nupkg
          dotnet nuget add source --username Stelzi79 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Stelzi79/index.json"
          dotnet nuget push .vs/bin/**/Release/*.nupkg -s github
      - name: Publish the package to nuget.org
        run: dotnet nuget push .vs/bin/**/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
